spring:
  application:
    name: frota-pro-integradora-winthor

  datasource:
    url: ${ORACLE_URL}
    username: ${ORACLE_USERNAME}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: frota-pro-integradora-winthor
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.frotasPro.integradora.winthor.dto"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

frotapro:
  kafka:
    topics:
      carga-sync-request: frotapro.carga.sync.request
      carga-sync-response: frotapro.carga.sync.response

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO
    br.com.frotasPro.integradora.winthor: DEBUG
